---
- name: A Playbook to install a specified package
  hosts: all
  become: true
  vars:
    package: tree

  tasks:

    - name: install "{{ package }}"
      yum:
        name: "{{ package }}"
        state: latest
  
