---
- name: A Playbook to remove a specified package
  hosts: all
  become: true
  vars:
    package: tree

  tasks:

    - name: Remove package: "{{ package }}"
      yum:
        name: "{{ package }}"
        state: absent
  
